version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock_api
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: ["--verbose"]

volumes:
  mongo_data:
